// <auto-generated />
namespace SocialMediasAssistant.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UniqueLinks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UniqueLinks));
        
        string IMigrationMetadata.Id
        {
            get { return "201809190119390_UniqueLinks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
