//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your account settings.
        /// </summary>
        public static string AccountSettings {
            get {
                return ResourceManager.GetString("AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add account.
        /// </summary>
        public static string AddAccount {
            get {
                return ResourceManager.GetString("AddAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string AddAccountConfirm {
            get {
                return ResourceManager.GetString("AddAccountConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Facebook Post.
        /// </summary>
        public static string AddFacebookPost {
            get {
                return ResourceManager.GetString("AddFacebookPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Page.
        /// </summary>
        public static string AddPage {
            get {
                return ResourceManager.GetString("AddPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Post.
        /// </summary>
        public static string AddPost {
            get {
                return ResourceManager.GetString("AddPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string AssociateProviderAfter {
            get {
                return ResourceManager.GetString("AssociateProviderAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate your.
        /// </summary>
        public static string AssociateProviderPrev {
            get {
                return ResourceManager.GetString("AssociateProviderPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association Form.
        /// </summary>
        public static string AssociationForm {
            get {
                return ResourceManager.GetString("AssociationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AuthenticationSuccessAfter {
            get {
                return ResourceManager.GetString("AuthenticationSuccessAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with.
        /// </summary>
        public static string AuthenticationSuccessPrev {
            get {
                return ResourceManager.GetString("AuthenticationSuccessPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Post.
        /// </summary>
        public static string ChoosePost {
            get {
                return ResourceManager.GetString("ChoosePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email. Please.
        /// </summary>
        public static string ConfirmedEmail {
            get {
                return ResourceManager.GetString("ConfirmedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Log in.
        /// </summary>
        public static string ConfirmedEmailLink {
            get {
                return ResourceManager.GetString("ConfirmedEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Logins.
        /// </summary>
        public static string CurrentLogins {
            get {
                return ResourceManager.GetString("CurrentLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already added this post or page.
        /// </summary>
        public static string DuplicatePost {
            get {
                return ResourceManager.GetString("DuplicatePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn points liking facebook pages.
        /// </summary>
        public static string EarnPointsFacebookPages {
            get {
                return ResourceManager.GetString("EarnPointsFacebookPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn points liking facebook posts.
        /// </summary>
        public static string EarnPointsFacebookPosts {
            get {
                return ResourceManager.GetString("EarnPointsFacebookPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earn points liking Instagram posts.
        /// </summary>
        public static string EarnPointsInstagramPosts {
            get {
                return ResourceManager.GetString("EarnPointsInstagramPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Logins.
        /// </summary>
        public static string ExternalLogins {
            get {
                return ResourceManager.GetString("ExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Page.
        /// </summary>
        public static string FacebookPage {
            get {
                return ResourceManager.GetString("FacebookPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Posts.
        /// </summary>
        public static string FacebookPosts {
            get {
                return ResourceManager.GetString("FacebookPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow users.
        /// </summary>
        public static string FollowUsers {
            get {
                return ResourceManager.GetString("FollowUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Facebook likes.
        /// </summary>
        public static string GetFacebookLikes {
            get {
                return ResourceManager.GetString("GetFacebookLikes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using Budaliken you can increase the number of likes of your posts through Facebook..
        /// </summary>
        public static string GetFacebookLikesInfo {
            get {
                return ResourceManager.GetString("GetFacebookLikesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get followers.
        /// </summary>
        public static string GetFollowers {
            get {
                return ResourceManager.GetString("GetFollowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanna increase the number of followers? Go ahead.
        /// </summary>
        public static string GetFollowersInfo {
            get {
                return ResourceManager.GetString("GetFollowersInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Instagram favs.
        /// </summary>
        public static string GetInstagramFavs {
            get {
                return ResourceManager.GetString("GetInstagramFavs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budaliken allows you to increase the favs of your post in Instagram.
        /// </summary>
        public static string GetInstagramFavsInfo {
            get {
                return ResourceManager.GetString("GetInstagramFavsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this area to provide additional information..
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram post.
        /// </summary>
        public static string InstagramPost {
            get {
                return ResourceManager.GetString("InstagramPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budaliken is a website for increasing
        ///        likes, followers, favs and etc. in sites like
        ///        Facebook, Instagram.
        /// </summary>
        public static string JumbotronInfo {
            get {
                return ResourceManager.GetString("JumbotronInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like pages.
        /// </summary>
        public static string LikePages {
            get {
                return ResourceManager.GetString("LikePages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like posts.
        /// </summary>
        public static string LikePosts {
            get {
                return ResourceManager.GetString("LikePosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link is required.
        /// </summary>
        public static string LinkRequired {
            get {
                return ResourceManager.GetString("LinkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        public static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your external logins.
        /// </summary>
        public static string ManageLogins {
            get {
                return ResourceManager.GetString("ManageLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link is not valid.
        /// </summary>
        public static string NotValidLink {
            get {
                return ResourceManager.GetString("NotValidLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Logins.
        /// </summary>
        public static string OtherLogins {
            get {
                return ResourceManager.GetString("OtherLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string Pages {
            get {
                return ResourceManager.GetString("Pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points should be between 5 and 100.
        /// </summary>
        public static string PointsRange {
            get {
                return ResourceManager.GetString("PointsRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points are required.
        /// </summary>
        public static string PointsRequired {
            get {
                return ResourceManager.GetString("PointsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts.
        /// </summary>
        public static string Posts {
            get {
                return ResourceManager.GetString("Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered logins.
        /// </summary>
        public static string RegisteredLogins {
            get {
                return ResourceManager.GetString("RegisteredLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a user name for this site below and click the Register button to finish logging in..
        /// </summary>
        public static string RequestUsername {
            get {
                return ResourceManager.GetString("RequestUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your page.
        /// </summary>
        public static string SelectPage {
            get {
                return ResourceManager.GetString("SelectPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
    }
}
